# Site settings
title: CIS400
baseurl: "cis400-f21" #"cis352"
url: "https://kmicinski.com/"
description: "CMSC400--Introduction to Compiler Construction (Fall '21) at Syracuse"
permalink: pretty

# Build settings
#markdown: redcarpet

# Build posts to appear in the future
future: true

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
